import { Analytics } from '@vercel/analytics/react' // Analytics tracks how many visitors come to myjobsinsouthsudan, which pages they click on, and where your traffic is coming from.
import { SpeedInsights } from '@vercel/speed-insights/next' // SpeedInsights monitors how fast your website loads for actual users in South Sudan. If page speeds drop due to low bandwidth or heavy images, this tool alerts you so you can optimize it.
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'], display: 'swap' })



export const metadata: Metadata = {
  title: "MyJobsInSouthSudan | Find Your Next Career Move",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.className} h-full antialiased`}
    >
      <body className="min-h-screen flex flex-col w-full bg-[#feffff] text-[#0f172a] antialiased">
        <div className="flex-1 w-full">
          <Navbar />
          {children}
        </div>
        <Analytics />
        <SpeedInsights />
        <Footer />
      </body>
    </html>
  );
}
